config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :companies
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :owner_id, :company_number, :status, :ourgoal, :whatwedo)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :company_id, :status, :images, :catch_copy, :discription, :strong_point, :rv_whole, :rv_cost, :rv_support, :rv_maintenability, :tv_experience, :rv_simplisity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :status, :company_number, :position, :whoiam)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.number_field :owner_id, id: :company_owner_id %>
  </div>

  <div class="field">
    <%= form.label :company_number %>
    <%= form.number_field :company_number, id: :company_company_number %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :company_status %>
  </div>

  <div class="field">
    <%= form.label :ourgoal %>
    <%= form.text_area :ourgoal, id: :company_ourgoal %>
  </div>

  <div class="field">
    <%= form.label :whatwedo %>
    <%= form.text_area :whatwedo, id: :company_whatwedo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Company number</th>
      <th>Status</th>
      <th>Ourgoal</th>
      <th>Whatwedo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.owner_id %></td>
        <td><%= company.company_number %></td>
        <td><%= company.status %></td>
        <td><%= company.ourgoal %></td>
        <td><%= company.whatwedo %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @company.owner_id %>
</p>

<p>
  <strong>Company number:</strong>
  <%= @company.company_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Ourgoal:</strong>
  <%= @company.ourgoal %>
</p>

<p>
  <strong>Whatwedo:</strong>
  <%= @company.whatwedo %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bamboo0</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :service_name %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.number_field :company_id, id: :service_company_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :service_status %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_area :images, id: :service_images %>
  </div>

  <div class="field">
    <%= form.label :catch_copy %>
    <%= form.text_field :catch_copy, id: :service_catch_copy %>
  </div>

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_area :discription, id: :service_discription %>
  </div>

  <div class="field">
    <%= form.label :strong_point %>
    <%= form.text_area :strong_point, id: :service_strong_point %>
  </div>

  <div class="field">
    <%= form.label :rv_whole %>
    <%= form.number_field :rv_whole, id: :service_rv_whole %>
  </div>

  <div class="field">
    <%= form.label :rv_cost %>
    <%= form.number_field :rv_cost, id: :service_rv_cost %>
  </div>

  <div class="field">
    <%= form.label :rv_support %>
    <%= form.number_field :rv_support, id: :service_rv_support %>
  </div>

  <div class="field">
    <%= form.label :rv_maintenability %>
    <%= form.number_field :rv_maintenability, id: :service_rv_maintenability %>
  </div>

  <div class="field">
    <%= form.label :tv_experience %>
    <%= form.number_field :tv_experience, id: :service_tv_experience %>
  </div>

  <div class="field">
    <%= form.label :rv_simplisity %>
    <%= form.number_field :rv_simplisity, id: :service_rv_simplisity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Status</th>
      <th>Images</th>
      <th>Catch copy</th>
      <th>Discription</th>
      <th>Strong point</th>
      <th>Rv whole</th>
      <th>Rv cost</th>
      <th>Rv support</th>
      <th>Rv maintenability</th>
      <th>Tv experience</th>
      <th>Rv simplisity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.company_id %></td>
        <td><%= service.status %></td>
        <td><%= service.images %></td>
        <td><%= service.catch_copy %></td>
        <td><%= service.discription %></td>
        <td><%= service.strong_point %></td>
        <td><%= service.rv_whole %></td>
        <td><%= service.rv_cost %></td>
        <td><%= service.rv_support %></td>
        <td><%= service.rv_maintenability %></td>
        <td><%= service.tv_experience %></td>
        <td><%= service.rv_simplisity %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @service.company_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @service.status %>
</p>

<p>
  <strong>Images:</strong>
  <%= @service.images %>
</p>

<p>
  <strong>Catch copy:</strong>
  <%= @service.catch_copy %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @service.discription %>
</p>

<p>
  <strong>Strong point:</strong>
  <%= @service.strong_point %>
</p>

<p>
  <strong>Rv whole:</strong>
  <%= @service.rv_whole %>
</p>

<p>
  <strong>Rv cost:</strong>
  <%= @service.rv_cost %>
</p>

<p>
  <strong>Rv support:</strong>
  <%= @service.rv_support %>
</p>

<p>
  <strong>Rv maintenability:</strong>
  <%= @service.rv_maintenability %>
</p>

<p>
  <strong>Tv experience:</strong>
  <%= @service.tv_experience %>
</p>

<p>
  <strong>Rv simplisity:</strong>
  <%= @service.rv_simplisity %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :user_status %>
  </div>

  <div class="field">
    <%= form.label :company_number %>
    <%= form.number_field :company_number, id: :user_company_number %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, id: :user_position %>
  </div>

  <div class="field">
    <%= form.label :whoiam %>
    <%= form.text_area :whoiam, id: :user_whoiam %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Status</th>
      <th>Company number</th>
      <th>Position</th>
      <th>Whoiam</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.status %></td>
        <td><%= user.company_number %></td>
        <td><%= user.position %></td>
        <td><%= user.whoiam %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Company number:</strong>
  <%= @user.company_number %>
</p>

<p>
  <strong>Position:</strong>
  <%= @user.position %>
</p>

<p>
  <strong>Whoiam:</strong>
  <%= @user.whoiam %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>